UPLOAD_FOLDER = "from-client"
DOWNLOAD_FOLDER = "to-client"
ARCHIVE_FOLDER = "data-archive"
GRAPH_FOLDER = "static/graphs"
RAW_DIR = "0_raw"
RAW_ZDB_DIR = "6_raw_zdb"
FINAL_SCORED_DIR = "5_final_lstm/"
FINAL_SCORED_ZDB_DIR = "9_final_zdb_lstm/"
ALLOWED_EXTENSIONS = {'ZIP':'.zip', 'XLS':'.xls', 'XLSX':'.xlsx', 'ZDB':'.zdb'}
MODELS = {'LSTM Rat Model':'rat_lstm_WIN-9.h5', 'LSTM Mice Model':'mice_lstm_WIN-9.h5'}
ADMIN_USERS = ['andrewsmith1025@gmail.com', 'musa.mazeem@gmail.com']