"""empty message

Revision ID: 164ff7758241
Revises: b90426954b78
Create Date: 2022-05-23 12:14:33.796415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164ff7758241'
down_revision = 'b90426954b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_user_emails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_user_emails',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
