"""logs is_deleted

Revision ID: 35619ca36565
Revises: 
Create Date: 2022-05-31 12:30:38.629911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35619ca36565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_log', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoring_log', 'is_deleted')
    # ### end Alembic commands ###
